/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */

/**
 * Contains post-processing transformations applied to an AST generated by the parser. These simplify the AST for easier planning, and
 * perform grammar level macro substitutions.
 */
package org.opensearch.tsdb.lang.m3.m3ql.parser.transform;
